server:
  port: 4052
spring:
  datasource:
    url: jdbc:mysql://192.168.154.31:30010/logic_runtime_demo?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: dbx
    password: 1234@qwer
