server:
  port: 4052
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logic_demo?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12#$qwER
#    url: jdbc:mysql://192.168.51.15:21900/dev_hs_wms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: dba
#    password: 1234*Qwer@xYz
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/public/web
logic:
  config-dir: ../logic-configs
  scan-package-names: com.aims.logic.service.demo