server:
  port: 4052
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logic_demo?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12#$qwER
#    url: jdbc:mysql://192.168.154.31:30010/dev_hs_wms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: dbx
#    password: 1234@qwer
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/public/web
logic:
  config-dir: /Users/lk/Documents/Dev/aims/xuanwu-logic/logic-solution/logic-configs
  scan-package-names: com.aims.logic.service.demo