server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logic_test?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12#$qwER
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.153.92:30010/hs_wms_xn?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: pxc.aims.com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logic:
  config-dir: /Users/lk/Documents/Dev/aims/xuanwu-logic/logic-solution/test-suite/test-case-configs
  scan-package-names: com.aims.logic.testsuite
  biz-error-classes: com.aims.logic.testsuite.demo.exception.CustomException
  item:
    groups:
      - name: 公共组件
        shape: ExtShape1