server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logic_test?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12#$qwER
#    url: jdbc:mysql://localhost:3306/logic_v0_7?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: 12#$qwER
#    url: jdbc:mysql://192.168.51.199:3307/bssg_wmsdb_test?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: 1q2w3e
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logic:
  log:
    store: db
    es:
      host: http://192.168.51.17:21903
      index: logic-log-test
  config-dir: /Users/lk/Documents/Dev/aims/xuanwu-logic/logic-solution/test-suite/test-case-configs
  scan-package-names: com.aims.logic.testsuite
  biz-error-classes: com.aims.logic.testsuite.demo.exception.CustomException
  item:
    groups:
      - name: 公共组件
        shape: ExtShape1
  biz-lock:
    type: memory  # 可选值：memory, redis
    spin-lock:
      wait-time: 0
      retry-times: 1
    redis: # type为redis时必填
      host: 192.168.53.205  # 地址
      port: 6379  # 端口号
      database: 1  # 数据库索引（默认为0）
      expire: 30
