server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logic_test?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12#$qwER
  #    url: jdbc:mysql://localhost:3306/logic_v0_7?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
  #    username: root
  #    password: 12#$qwER
  #    url: jdbc:mysql://192.168.51.199:3307/bssg_wmsdb_test?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
  #    username: root
  #    password: 1q2w3e
  redis:
    # 单节点配置
    host: localhost
    port: 6379
    password: your_password
    database: 0
    # 集群模式配置（单节点与集群模式二选一）
    # cluster:
    #   nodes:
    #     - 192.168.1.100:6379
    #     - 192.168.1.101:6379
    #   max-redirects: 3
logic:
  log:
    store: es
    es:
      #      host: http://192.168.51.17:21903
      #      index: logic-log-test
      host: http://192.168.51.201:9200
      index: logic-log-wms-test-mxd-new
  test:
    case:
  config-dir: /Users/lk/Documents/Dev/aims/xuanwu-logic/logic-solution/test-suite/test-case-configs
  scan-package-names: com.aims.logic.testsuite
  biz-error-classes: com.aims.logic.testsuite.demo.exception.CustomException
  item:
    groups:
      - name: 公共组件
        shape: ExtShape1
  biz-lock:
    expire: 30 # 单位：秒，根据业务请求响应时间来设置锁失效时间
    type: memory  # 可选值：memory, redis
    spin-lock:
      wait-time: 0
      retry-times: 1
