server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logic_test?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
#    url: jdbc:mysql://localhost:3306/logic_test_0_9?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12#$qwER
  #    url: jdbc:mysql://192.168.51.199:3307/bssg_wmsdb_test?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
  #    username: root
  #    password: 1q2w3e
logic:
  log:
    store: es
    item-queue-size: 30
    es:
      host: http://es.xuanwu-factory.dev.aimstek.cn
      index: logic-log-cbb-154
  #      username: admin
  #      password: idw
  test:
    case:
  config-dir: /Users/lk/Documents/Dev/aims/xuanwu-logic/logic-solution/test-suite/test-case-configs
  scan-package-names: com.aims.logic.testsuite
  biz-error-classes: com.aims.logic.testsuite.demo.exception.CustomException,java.sql.SQLIntegrityConstraintViolationException
  item:
    groups:
      - name: 公共组件w
        shape: ExtShape1
#  biz-lock:
#    spin-lock: # 自旋锁配置
#      wait-time: 0  #自旋每次等待时间
#      retry-times: 1 #自旋重试次数
#    expire: -1 # 单位：秒，根据业务请求响应时间来设置锁失效时间
#    type: memory  # 可选值：memory, redis
#    redis: # type为redis时必填
#      host: 192.168.53.205  # 地址
#      port: 6379  # 端口号
#      database: 1  # 数据库索引
#      password: aims1@034
#      cluster:
#        nodes:
#          - "192.168.153.77:16379"
#          - "192.168.153.78:16379"
#          - "192.168.153.79:16379"

