
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.154.31:30010/logic_runtime_demo?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    #    url: jdbc:mysql://192.168.154.31:30010/biz_asset_center?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    #    username: dbx
    #    password: 1234@qwer
    url: jdbc:mysql://localhost:3306/logic_demo?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12#$qwER
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/public/web
server:
  port: 4055
logic:
  config-dir: /Users/lk/Documents/Dev/aims/xuanwu-logic/logic-solution/logic-configs
  annotation: service
  scan-package-names: com.aims.logic.sdk.test,com.aims.logic.service.demo